auto-version:
  tags:
    - versioning
  only:
   - master
  script:
    - echo "Versioning automation process..."
    - git fetch --unshallow
    - git switch $CI_COMMIT_BRANCH
    - echo "List some debug information..."
    - git status --verbose
    - git branch --list --all
    - git tag --list
    - git describe --tags --abbrev=0 2>/dev/null
    - git rev-parse --short HEAD
    - ./config.sh --oscam-revision
    - ./config.sh --oscam-commit

    - echo "Setting up git properties..."
    - git config user.name "pipeline-user"
    - git config user.email "pipeline-user@users.noreply.git.streamboard.tv"

    - echo "Calculating new tag value..."
    - curr_tag=$(git describe --tags --abbrev=0 2>/dev/null)
    - new_tag=$(( $curr_tag + 1 ))

    - echo "Updating version information in globals.h..."
    - sed -i "/# define CS_SVN_VERSION/s/.*/# define CS_SVN_VERSION\t\t\t\"$new_tag\"/" globals.h
    - git diff globals.h
    - git add globals.h
    - git commit --amend --no-edit
    - sha=$(git rev-parse HEAD)

    - if git tag --list | grep -iq "$new_tag"; then
        echo "Removing existing tag:$new_tag...";
        git tag --delete "$new_tag";
        git push "http://version-pipeline:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" --delete "$new_tag" -o ci.skip;
      fi;

    - echo "Creating new tag:$new_tag on sha:$sha..."
    - git tag --annotate "$new_tag" -m "Revision $new_tag" "$sha"

    - echo "Pushing forced changes to repo..."
    - git push --force --follow-tags "http://version-pipeline:${GIT_PUSH_TOKEN}@${CI_REPOSITORY_URL#*@}" HEAD:$CI_COMMIT_BRANCH -o ci.skip
    - echo "Versioning automation complete."
