include:
  - local: .gitlab/oscam-helper.yml

variables:
  FF_USE_FASTZIP: 1
  TRANSFER_METER_FREQUENCY: "2s"
  ARTIFACT_COMPRESSION_LEVEL: "default"
  CACHE_COMPRESSION_LEVEL: "default"
  CACHE_REQUEST_TIMEOUT: 5

stages:
  - build
  - test
  - fixup
  - new-version

info:
  stage: .pre
  tags:
    - build
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $GITLAB_USER_NAME != 'pipeline-user'
  script:
    - !reference [.helper, runner-info]
  allow_failure: true

setup:
  stage: .pre
  tags:
    - build
  variables:
    GIT_STRATEGY: none
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - !reference [.helper, runner-setup]
  allow_failure: true

oscam-make-build:
  stage: build
  tags:
    - build
  variables:
    OSCAM_BUILD: "make"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - !reference [.helper, custom-checkout]
    - !reference [.helper, oscam-make]
  artifacts:
    paths:
      - build/oscam-${OSCAM_BUILD}
      - build/oscam-${OSCAM_BUILD}-build.log
    expire_in: 1 week
  allow_failure: true

oscam-cmake-build:
  stage: build
  tags:
    - build
  variables:
    OSCAM_BUILD: "cmake"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - !reference [.helper, custom-checkout]
    - !reference [.helper, oscam-cmake]
  artifacts:
    paths:
      - build/oscam-${OSCAM_BUILD}
      - build/oscam-${OSCAM_BUILD}-build.log
    expire_in: 1 week
  allow_failure: true

oscam-make-test:
  stage: test
  tags:
    - test
  needs: [oscam-make-build]
  variables:
    GIT_STRATEGY: none
    OSCAM_BUILD: "make"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - !reference [.helper, oscam-startup-test]
  artifacts:
    paths:
      - build/oscam-${OSCAM_BUILD}-test.log
    expire_in: 1 week
  allow_failure: true

oscam-cmake-test:
  stage: test
  tags:
    - test
  needs: [oscam-cmake-build]
  variables:
    GIT_STRATEGY: none
    OSCAM_BUILD: "cmake"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'schedule'
  script:
    - !reference [.helper, oscam-startup-test]
  allow_failure: true
  artifacts:
    paths:
      - build/oscam-${OSCAM_BUILD}-test.log
    expire_in: 1 week

code-cleanup:
  stage: fixup
  tags:
    - clean
  needs: [oscam-make-build, oscam-cmake-build]
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $GITLAB_USER_NAME != 'pipeline-user'
    - if: $CI_PIPELINE_SOURCE == 'schedule' && $GITLAB_USER_NAME != 'pipeline-user'
  dependencies: []
  script:
    - !reference [.helper, fix-whitespaces]
  allow_failure: true

auto-version:
  stage: new-version
  tags:
    - version
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $GITLAB_USER_NAME != 'pipeline-user'
  script:
    - !reference [.helper, tag-version]
  allow_failure: false
